// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfrQJmcShwZsAO7yGjRR9lvu6cPyPnpqc',
    appId: '1:638163581320:web:9970289074d1206328e23d',
    messagingSenderId: '638163581320',
    projectId: 'recipebox-c1053',
    authDomain: 'recipebox-c1053.firebaseapp.com',
    storageBucket: 'recipebox-c1053.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtdDkeG-G5-aKsOvXFZAB0mH7sJdghBJE',
    appId: '1:638163581320:android:fea8162b3e228cc828e23d',
    messagingSenderId: '638163581320',
    projectId: 'recipebox-c1053',
    storageBucket: 'recipebox-c1053.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpbpqegMgS1Vcb4-fd3xc4IWJOvXmIh-0',
    appId: '1:638163581320:ios:e65a82efd3e848ec28e23d',
    messagingSenderId: '638163581320',
    projectId: 'recipebox-c1053',
    storageBucket: 'recipebox-c1053.appspot.com',
    iosClientId: '638163581320-m84ltulu49ledniusrub3s6bm1743090.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeBox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpbpqegMgS1Vcb4-fd3xc4IWJOvXmIh-0',
    appId: '1:638163581320:ios:8a1fe507fa59b55c28e23d',
    messagingSenderId: '638163581320',
    projectId: 'recipebox-c1053',
    storageBucket: 'recipebox-c1053.appspot.com',
    iosClientId: '638163581320-uerhceiilm1a35ro6ep0pqak9itsqne9.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeBox.RunnerTests',
  );
}
